title: ONTOS.RENT
description: Газета аренды вещей · Один предмет — один сигнал
baseurl: "/EasyMusicRent"
url: "https://ontoslive.github.io"
markdown: kramdown
permalink: pretty
exclude:
  - README.md
